// Classic mode: 120 levels in 9 worlds, ordered easy → hard. The first three
// worlds are recognisable shapes; each later world introduces one brick
// mechanic (its first level teaches it alone, via `hint`), and the last world
// mixes them all. Ball speed and paddle width scale with position in the list
// (see difficultyFor() in game.js).
//
// Map legend (one character per brick cell, 10 columns):
//   .  empty       #  normal       3  stone — breaks on the 3rd hit
//   I  iron — never breaks, not needed to finish the level
//   T  TNT — destroys the 8 bricks around it, chains into other TNT
//   K  key         L  lock — unbreakable until every key is gone
// `slide` lists row indexes that sweep left and right.
const CLASSIC_CHAPTERS = [
  {
    title: "Başlangıç",
    levels: [
      { name: "Piramit",       rows: 7, pattern: "pyramid" },
      { name: "Elmas",         rows: 7, pattern: "diamond" },
      { name: "Klasik Duvar",  rows: 5, pattern: "full" },
      { name: "Kalp",          pattern: "heart" },
      { name: "Yıldız",        pattern: "star" },
      { name: "Ağaç",          pattern: "tree" },
      { name: "Tekne",         pattern: "boat" },
      { name: "Taç",           pattern: "crown" },
      { name: "Ev",            pattern: "house" },
      { name: "Balon",         pattern: "balloon" },
    ],
  },
  {
    title: "Orta",
    levels: [
      { name: "Kalkan",        pattern: "shield" },
      { name: "Çan",           pattern: "bell" },
      { name: "Şemsiye",       pattern: "umbrella" },
      { name: "Ok",            rows: 7, pattern: "arrow" },
      { name: "Kupa",          pattern: "trophy" },
      { name: "Roket",         pattern: "rocket" },
      { name: "Hilal",         rows: 8, pattern: "crescent" },
      { name: "Kum Saati",     rows: 8, pattern: "hourglass" },
      { name: "Artı",          rows: 7, pattern: "plus" },
      { name: "Güneş",         pattern: "sun" },
    ],
  },
  {
    title: "Zor",
    levels: [
      { name: "Kılıç",         pattern: "sword" },
      { name: "Anahtar",       pattern: "key" },
      { name: "Çapa",          pattern: "anchor" },
      { name: "Kar Tanesi",    pattern: "snowflake" },
      { name: "Sonsuzluk",     rows: 7, pattern: "infinity" },
      { name: "Adalar",        rows: 8, pattern: "islands" },
      { name: "Dama Tahtası",  rows: 6, pattern: "checkerboard" },
      { name: "Hedef Tahtası", rows: 8, pattern: "target" },
      { name: "Labirent",      rows: 8, pattern: "maze" },
      { name: "Büyük Final",   rows: 9, pattern: "full" },
    ],
  },
  {
    title: "Taş Tuğlalar",
    levels: [
      { name: "İlk Çatlak", hint: "Gri taş tuğlalar üç vuruşta kırılır: her vuruşta çatlaklar büyür.", map: [
        "##########",
        "##########",
        "###3333###",
        "##########",
      ]},
      { name: "Taş Şeritler", map: [
        "3333333333",
        "##########",
        "##########",
        "3333333333",
      ]},
      { name: "Taş Piramit", map: [
        "....33....",
        "...3##3...",
        "..3####3..",
        ".3######3.",
        "3########3",
      ]},
      { name: "Taş Dama", map: [
        "#3#3#3#3#3",
        "3#3#3#3#3#",
        "#3#3#3#3#3",
        "3#3#3#3#3#",
      ]},
      { name: "Taş Çerçeve", map: [
        "3333333333",
        "3########3",
        "3#......#3",
        "3#......#3",
        "3########3",
        "#3#3#3#3#3",
      ]},
      { name: "Taş Başlıklı Sütunlar", map: [
        "33..33..33",
        "##..##..##",
        "##..##..##",
        "##..##..##",
        "33..33..33",
      ]},
      { name: "Taş Kalp", map: [
        ".33....33.",
        "3##3..3##3",
        "3########3",
        ".3######3.",
        "..3####3..",
        "...3##3...",
        "....33....",
      ]},
      { name: "Taş Kum Saati", map: [
        "33######33",
        ".3######3.",
        "..3####3..",
        "...3##3...",
        "..3####3..",
        ".3######3.",
        "33######33",
      ]},
      { name: "Mazgallı Sur", map: [
        "3.3.33.3.3",
        "##########",
        "##########",
        "##########",
      ]},
      { name: "Taş Elmas", map: [
        "....33....",
        "...3333...",
        "..33##33..",
        ".33####33.",
        "..33##33..",
        "...3333...",
        "....33....",
      ]},
      { name: "Katmanlar", map: [
        "##########",
        "3333333333",
        "##########",
        "##########",
        "3333333333",
      ]},
      { name: "Taş Ok", map: [
        "....33....",
        "...3333...",
        "..333333..",
        ".33333333.",
        "....33....",
        "....33....",
        "....33....",
      ]},
      { name: "Zikzak", map: [
        "33........",
        "3333......",
        "..3333....",
        "....3333..",
        "......3333",
        "........33",
      ]},
      { name: "Taş Kale", map: [
        "3.3....3.3",
        "333....333",
        "3#3####3#3",
        "3########3",
        "3###..###3",
        "3###..###3",
      ]},
      { name: "Taş Duvar", map: [
        "3333333333",
        "#3#3#3#3#3",
        "##########",
        "##########",
      ]},
    ],
  },
  {
    title: "Demir Duvarlar",
    levels: [
      { name: "İlk Demir", hint: "Perçinli demir tuğlalar kırılmaz. Bölümü bitirmek için onları kırman gerekmez; etraflarından dolaş.", map: [
        "##########",
        "##########",
        "###IIII###",
      ]},
      { name: "Demir Çizgi", map: [
        "##########",
        "##########",
        "##########",
        "I...II...I",
      ]},
      { name: "Demir Direkler", map: [
        "#I######I#",
        "#I######I#",
        "#I######I#",
        "#I######I#",
      ]},
      { name: "Zırhlı Merkez", map: [
        "..........",
        "...IIII...",
        "..I####I..",
        "..I#33#I..",
        "..I####I..",
      ]},
      { name: "Demir Dama", map: [
        "#I#I#I#I#I",
        "##########",
        "I#I#I#I#I#",
        "##########",
      ]},
      { name: "Oluk", map: [
        "IIII..IIII",
        "####..####",
        "####..####",
        "####..####",
      ]},
      { name: "Demir Kafes", map: [
        "I.I.I.I.I.",
        "##########",
        ".I.I.I.I.I",
        "##########",
        "I.I.I.I.I.",
      ]},
      { name: "Zırhlı Kalp", map: [
        ".II....II.",
        "I##I..I##I",
        "##########",
        ".########.",
        "..I####I..",
        "...####...",
      ]},
      { name: "Demir Labirent", map: [
        "IIIIIIII.I",
        "#........#",
        "#.IIIIII.#",
        "#.I####I.#",
        "#.I####I.#",
        "#.II..II.#",
        "#........#",
      ]},
      { name: "Demir Merdiven", map: [
        "II........",
        "##II......",
        "####II....",
        "######II..",
        "########II",
        "##########",
      ]},
      { name: "Kanal", map: [
        "#I######I#",
        "#I#3333#I#",
        "#I######I#",
        "#I......I#",
        "#I......I#",
      ]},
      { name: "Demir Çekirdekli Yıldız", map: [
        "....##....",
        "...####...",
        "..##II##..",
        "##########",
        ".########.",
        "###....###",
        "##......##",
      ]},
      { name: "Siperler", map: [
        "##########",
        "##########",
        ".II.II.II.",
        "..........",
        "##########",
      ]},
      { name: "Kasa", map: [
        "I3######3I",
        "I########I",
        "I3######3I",
        "II......II",
      ]},
      { name: "Demir Kale", map: [
        "I#I####I#I",
        "IIII##IIII",
        "#33####33#",
        "#3##II##3#",
        "#3######3#",
        "##I####I##",
      ]},
    ],
  },
  {
    title: "Patlayıcılar",
    levels: [
      { name: "İlk Fitil", hint: "Kırmızı TNT tuğlası kırılınca çevresindeki 8 tuğlayı da yok eder; yanındaki TNT'ler zincirleme patlar.", map: [
        "##########",
        "##########",
        "####TT####",
        "##########",
        "##########",
      ]},
      { name: "Dört Bomba", map: [
        "##########",
        "#T######T#",
        "##########",
        "#T######T#",
        "##########",
      ]},
      { name: "Zincir", map: [
        "T#########",
        "#T########",
        "##T#######",
        "###T######",
        "####T#####",
        "#####T####",
      ]},
      { name: "Barut Fıçısı", map: [
        "..######..",
        ".##3333##.",
        ".#3#TT#3#.",
        ".##3333##.",
        "..######..",
      ]},
      { name: "Mayın Tarlası", map: [
        "#.#.#.#.#.",
        ".T.#.#.T.#",
        "#.#.#.#.#.",
        ".#.T.T.#.#",
        "#.#.#.#.#.",
      ]},
      { name: "Demir ve Barut", map: [
        "II######II",
        "##########",
        "###T##T###",
        "##########",
        "II######II",
      ]},
      { name: "Çift Zincir", map: [
        "TT######TT",
        ".T######T.",
        "..T####T..",
        "...T##T...",
        "....TT....",
      ]},
      { name: "Havai Fişek", map: [
        "....##....",
        "...#TT#...",
        "..######..",
        ".###TT###.",
        "..######..",
        "...####...",
        "....##....",
      ]},
      { name: "Taş Zırh", map: [
        "3333333333",
        "3########3",
        "3##T##T##3",
        "3########3",
        "3333333333",
      ]},
      { name: "Tuzaklı Kasa", map: [
        "IIIIIIIIII",
        "I########I",
        "I#T####T#I",
        "I########I",
        "III#..#III",
      ]},
      { name: "Fitil Şeritleri", map: [
        "T#T#T#T#T#",
        "##########",
        "#T#T#T#T#T",
        "##########",
      ]},
      { name: "Patlama Çemberi", map: [
        "..T####T..",
        ".#......#.",
        "T..####..T",
        "#..#TT#..#",
        "T..####..T",
        ".#......#.",
        "..T####T..",
      ]},
      { name: "Dolu Depo", map: [
        "3T3T3T3T3T",
        "##########",
        "T3T3T3T3T3",
        "##########",
        "3T3T3T3T3T",
      ]},
      { name: "Sığınak", map: [
        "I.IIIIII.I",
        "I.I####I.I",
        "I.I#TT#I.I",
        "I.I####I.I",
        "I...##...I",
        "IIII..IIII",
      ]},
      { name: "Büyük Patlama", map: [
        "T##3333##T",
        "#3######3#",
        "##T####T##",
        "#3##TT##3#",
        "##T####T##",
        "#3######3#",
        "T##3333##T",
      ]},
    ],
  },
  {
    title: "Anahtar ve Kilit",
    levels: [
      { name: "İlk Anahtar", hint: "Mor kilitli tuğlalar kırılmaz. Altın anahtar tuğlaların hepsini kırınca kilitler açılır.", map: [
        "LLLLLLLLLL",
        "LLLLLLLLLL",
        "##########",
        "####KK####",
      ]},
      { name: "İki Anahtar", map: [
        "LLLLLLLLLL",
        "L########L",
        "L########L",
        "LLLLLLLLLL",
        "K........K",
      ]},
      { name: "Kilitli Kasa", map: [
        "..LLLLLL..",
        "..L####L..",
        "..L#33#L..",
        "..L####L..",
        "..LLLLLL..",
        "K........K",
      ]},
      { name: "Anahtar Kulesi", map: [
        "....KK....",
        "....##....",
        "LL..##..LL",
        "LL..##..LL",
        "LLLL##LLLL",
      ]},
      { name: "Kilit Dama", map: [
        "L#L#L#L#L#",
        "#L#L#L#L#L",
        "L#L#L#L#L#",
        "....KK....",
      ]},
      { name: "Demir Kapı", map: [
        "IIIIIIIIII",
        "I########I",
        "I#LLLLLL#I",
        "I#L3333L#I",
        "I#LLLLLL#I",
        "I##K..K##I",
      ]},
      { name: "Gizli Anahtar", map: [
        "##########",
        "#33333333#",
        "#3##KK##3#",
        "#33333333#",
        "##########",
      ]},
      { name: "Dört Kilit", map: [
        "LL##LL##LL",
        "LL##LL##LL",
        "##KK##KK##",
        "LL##LL##LL",
        "LL##LL##LL",
      ]},
      { name: "Kilitli Cephane", map: [
        "LLLLLLLLLL",
        "L##T##T##L",
        "L########L",
        "LLLLLLLLLL",
        "##T#KK#T##",
      ]},
      { name: "Kilitli Kalp", map: [
        ".LL....LL.",
        "L##L..L##L",
        "L########L",
        ".L######L.",
        "..L####L..",
        "...L##L...",
        "....KK....",
      ]},
      { name: "Kule Kapısı", map: [
        "I..LLLL..I",
        "I..L##L..I",
        "I..L##L..I",
        "I..LLLL..I",
        "I........I",
        "IIIK..KIII",
      ]},
      { name: "Kilitli Sütunlar", map: [
        "L#L#L#L#L#",
        "L#L#L#L#L#",
        "L#L#L#L#L#",
        "L#L#L#L#L#",
        "K.K.K.K.K.",
      ]},
      { name: "Üç Kat", map: [
        "LLLLLLLLLL",
        "3333333333",
        "LLLLLLLLLL",
        "##########",
        "LLLLKKLLLL",
      ]},
      { name: "Hazine Odası", map: [
        "IIIIIIIIII",
        "ILLLLLLLLI",
        "IL333333LI",
        "ILLLLLLLLI",
        "I##T##T##I",
        "I#K####K#I",
        "II......II",
      ]},
      { name: "Büyük Kilit", map: [
        "LLLLLLLLLL",
        "L33TTTT33L",
        "L3######3L",
        "LLLL##LLLL",
        "I#K####K#I",
        "I########I",
        "I...##...I",
      ]},
    ],
  },
  {
    title: "Kayan Sıralar",
    levels: [
      { name: "İlk Kayma", hint: "Bazı sıralar sağa sola kayar. Topu atmadan önce zamanlamanı ayarla.", slide: [2], map: [
        "##########",
        "##########",
        "...####...",
      ]},
      { name: "İki Kızak", slide: [1, 3], map: [
        "##########",
        "..######..",
        "##########",
        "..######..",
      ]},
      { name: "Sarkaç", slide: [0, 1, 2], map: [
        "....##....",
        "...####...",
        "..######..",
        "##########",
      ]},
      { name: "Taş Kızak", slide: [1, 3], map: [
        "##########",
        "...3333...",
        "##########",
        "...3333...",
      ]},
      { name: "Konvoy", slide: [0, 1, 2], map: [
        "##........",
        "....##....",
        "........##",
        "##########",
        "##########",
      ]},
      { name: "Demir Perde", slide: [3], map: [
        "##########",
        "##########",
        "III....III",
        "..######..",
      ]},
      { name: "Dalga", slide: [0, 1, 2, 3, 4], map: [
        "..######..",
        "...####...",
        "..######..",
        "...####...",
        "..######..",
      ]},
      { name: "Kayan Bombalar", slide: [3], map: [
        "##########",
        "###T##T###",
        "##########",
        "...#TT#...",
      ]},
      { name: "Dar Geçit", slide: [3], map: [
        "##########",
        "##########",
        "III....III",
        "...####...",
      ]},
      { name: "Anahtar Kızağı", slide: [3], map: [
        "LLLLLLLLLL",
        "L########L",
        "LLLLLLLLLL",
        "....KK....",
      ]},
      { name: "Taş Konvoy", slide: [0, 1, 2], map: [
        "3333......",
        "......3333",
        "3333......",
        "##########",
      ]},
      { name: "Kayan Merdiven", slide: [0, 1, 2, 3, 4], map: [
        "##........",
        "..##......",
        "....##....",
        "......##..",
        "........##",
      ]},
      { name: "Hareketli Hedef", slide: [1], map: [
        "..........",
        "....TT....",
        "##########",
        "##########",
        ".########.",
      ]},
      { name: "Karşı Akıntı", slide: [1, 3], map: [
        ".########.",
        "..######..",
        ".########.",
        "..######..",
        ".########.",
      ]},
      { name: "Kızak Finali", slide: [1, 3, 5], map: [
        "IIII..IIII",
        "...3333...",
        "##########",
        "..#T##T#..",
        "##########",
        "...3333...",
      ]},
    ],
  },
  {
    title: "Büyük Karışım",
    levels: [
      { name: "Karışık Başlangıç", hint: "Son dünya: taş, demir, TNT, anahtar ve kayan sıralar bir arada.", map: [
        "3#3#3#3#3#",
        "##########",
        "I#T####T#I",
        "##########",
      ]},
      { name: "Mühimmat Deposu", map: [
        "IIIIIIIIII",
        "I3T3T3T3TI",
        "I########I",
        "II##..##II",
      ]},
      { name: "Anahtarlı Kale", map: [
        "LLLLLLLLLL",
        "L3##TT##3L",
        "LLLL##LLLL",
        "I#K####K#I",
        "I########I",
      ]},
      { name: "Zırhlı Kızak", slide: [2], map: [
        "IIIIIIIIII",
        "##########",
        "..#3333#..",
        "##########",
      ]},
      { name: "Karışık Kum Saati", map: [
        "3333333333",
        ".3##TT##3.",
        "..I####I..",
        "...I##I...",
        "..I####I..",
        ".3######3.",
        "3333333333",
      ]},
      { name: "Zincirleme Kilit", map: [
        "LLLLLLLLLL",
        "LT######TL",
        "LLLLLLLLLL",
        "T##K##K##T",
      ]},
      { name: "Sur Kapısı", map: [
        "#3#3#3#3#3",
        "##########",
        "##########",
        "III....III",
        "..T....T..",
      ]},
      { name: "Kayan Yıldız", slide: [0, 3], map: [
        "....##....",
        "..######..",
        "##########",
        "..##TT##..",
        ".##....##.",
      ]},
      { name: "Hazine Kızağı", slide: [5], map: [
        "IIIIIIIIII",
        "ILLLLLLLLI",
        "IL3TTTT3LI",
        "ILLLLLLLLI",
        "..........",
        "...K##K...",
      ]},
      { name: "Demir Geçitler", map: [
        "I.I....I.I",
        "##########",
        "#3#IIII#3#",
        "#T#....#T#",
        "##########",
        "...I..I...",
      ]},
      { name: "Barut Yolu", map: [
        "T.T.T.T.T.",
        "#3#3#3#3#3",
        ".T.T.T.T.T",
        "3#3#3#3#3#",
      ]},
      { name: "Çift Kasa", map: [
        "IIII##IIII",
        "I33ILLI33I",
        "I#KILLIK#I",
        "I##ILLI##I",
        "I..I..I..I",
        "##########",
      ]},
      { name: "Fırtına", slide: [0, 3], map: [
        "..######..",
        "T########T",
        ".3######3.",
        "..######..",
        "I........I",
      ]},
      { name: "Son Kale", map: [
        "IIIIIIIIII",
        "IT######TI",
        "I3LLLLLL3I",
        "I3L####L3I",
        "I3LLLLLL3I",
        "I33K..K33I",
        "II......II",
      ]},
      { name: "Büyük Karışım Finali", slide: [5], map: [
        "I3I####I3I",
        "T########T",
        "3LLLLLLLL3",
        "3L#TTTT#L3",
        "3LLLLLLLL3",
        "..#K##K#..",
        "##########",
      ]},
    ],
  },
];
