// History mode: a chronological campaign from the Asian Huns to 1939.
// Each level's bricks spell out the event's year; the note is shown on a text
// card before the level starts. Each era has its own brick palette (top → bottom
// row) so the campaign visibly moves through time without background images.
const HISTORY_CHAPTERS = [
  {
    title: "İlk Türk Devletleri",
    rowColors: ["#f5ddb0", "#e8c288", "#d1a165", "#b17f48", "#8c6238", "#664829", "#40301c"],
    levels: [
      { year: "MÖ 220", digits: "220", name: "Büyük Hun Devleti",
        note: "Bilinen ilk Türk devleti Teoman Yabgu döneminde tarih sahnesine çıktı." },
      { year: "MÖ 209", digits: "209", name: "Mete Han",
        note: "Mete Han tahta geçti; orduyu onlu sisteme göre düzenleyerek Hunları bozkırın en güçlü devleti yaptı." },
      { year: "375", digits: "375", name: "Kavimler Göçü",
        note: "Balamir önderliğindeki Hunlar Karadeniz'in kuzeyine ilerledi; başlayan göç dalgası Avrupa'nın haritasını değiştirdi." },
      { year: "552", digits: "552", name: "Göktürk Devleti",
        note: "Bumin Kağan Avarları yenerek Göktürk Devleti'ni kurdu. 'Türk' adını resmî devlet adı olarak kullanan ilk devlet." },
      { year: "630", digits: "630", name: "Fetret Yılları",
        note: "Doğu Göktürkleri Çin hâkimiyetine girdi; bağımsızlık mücadelesi yaklaşık yarım yüzyıl sürdü." },
      { year: "682", digits: "682", name: "II. Göktürk Devleti",
        note: "Kutluk (İlteriş) Kağan Çin egemenliğine son verip II. Göktürk Devleti'ni kurdu." },
      { year: "732", digits: "732", name: "Orhun Yazıtları",
        note: "Kül Tigin anısına Göktürk alfabesiyle yazılan yazıt dikildi; Bilge Kağan ve Tonyukuk yazıtlarıyla birlikte Türk tarihinin ilk yazılı belgeleri arasında sayılır." },
      { year: "744", digits: "744", name: "Uygur Devleti",
        note: "Uygurlar Göktürk Devleti'nin yerine kendi devletlerini kurdu; şehirler kuran, yerleşik hayata geçen bir Türk devleti oldular." },
      { year: "751", digits: "751", name: "Talas Savaşı",
        note: "Karlukların desteklediği Abbasi ordusu Çin'i yendi; Orta Asya'da Türk–İslam yakınlaşması hızlandı." },
    ],
  },
  {
    title: "Türk-İslam Devletleri ve Selçuklular",
    rowColors: ["#e8e2d0", "#cfc4a8", "#b8a06c", "#9c8354", "#7c6a42", "#5a4a30", "#3a3020"],
    levels: [
      { year: "840", digits: "840", name: "Karahanlı Devleti",
        note: "Uygur Devleti'nin yıkılmasının ardından kurulan Karahanlılar, İslamiyet'i devlet dini olarak kabul eden ilk Türk devleti oldu." },
      { year: "963", digits: "963", name: "Gazneli Devleti",
        note: "Alp Tigin Gazne'de bağımsız bir devlet kurdu; Gazneliler Sultan Mahmud döneminde Hindistan seferleriyle en parlak çağlarını yaşadı." },
      { year: "1040", digits: "1040", name: "Dandanakan Savaşı",
        note: "Tuğrul ve Çağrı Beyler Gaznelileri yendi; Büyük Selçuklu Devleti resmen kuruldu." },
      { year: "1048", digits: "1048", name: "Pasinler Savaşı",
        note: "Selçuklular Bizans ordusunu Pasinler'de yendi; Bizans'a karşı kazanılan ilk büyük zafer." },
      { year: "1069", digits: "1069", name: "Kutadgu Bilig",
        note: "Yusuf Has Hacib 'mutluluk veren bilgi' anlamına gelen Kutadgu Bilig'i tamamlayıp Karahanlı hükümdarına sundu." },
      { year: "1071", digits: "1071", name: "Malazgirt Meydan Muharebesi",
        note: "Sultan Alparslan Bizans İmparatoru Romen Diyojen'i yendi; Anadolu'nun kapıları Türklere açıldı." },
      { year: "1072", digits: "1072", name: "Divanü Lügati't-Türk",
        note: "Kaşgarlı Mahmud, Türkçeyi Araplara öğretmek için Türkçenin bilinen ilk sözlüğünü yazmaya başladı." },
      { year: "1075", digits: "1075", name: "Türkiye Selçuklu Devleti",
        note: "Kutalmışoğlu Süleyman Şah İznik'i başkent yaparak Türkiye Selçuklu Devleti'ni kurdu." },
      { year: "1141", digits: "1141", name: "Katvan Savaşı",
        note: "Sultan Sencer Karahıtaylara yenildi; Büyük Selçuklu Devleti'nin çöküşü hızlandı." },
      { year: "1176", digits: "1176", name: "Miryokefalon Savaşı",
        note: "II. Kılıç Arslan Bizans'ı yendi; Bizans Anadolu'yu geri alma umudunu yitirdi." },
      { year: "1230", digits: "1230", name: "Yassıçemen Savaşı",
        note: "Alaeddin Keykubad Harezmşah Celaleddin'i yendi; Anadolu ile Moğollar arasındaki tampon devlet ortadan kalktı." },
      { year: "1243", digits: "1243", name: "Kösedağ Savaşı",
        note: "Anadolu Selçukluları Moğollara yenildi; Anadolu'da beylikler dönemine giden yol açıldı." },
    ],
  },
  {
    title: "Osmanlı: Kuruluş ve Yükseliş",
    rowColors: ["#f2d9a0", "#e0b876", "#c99356", "#a8703f", "#7a4f34", "#523829", "#33241c"],
    levels: [
      { year: "1299", digits: "1299", name: "Osmanlı Beyliği",
        note: "Osman Bey önderliğinde Osmanlı Beyliği kuruldu (geleneksel kuruluş tarihi)." },
      { year: "1302", digits: "1302", name: "Koyunhisar Savaşı",
        note: "Osman Bey Bizans ordusunu Koyunhisar'da (Bafeus) yendi; Osmanlı'nın ilk büyük zaferi." },
      { year: "1326", digits: "1326", name: "Bursa'nın Fethi",
        note: "Orhan Bey Bursa'yı aldı; şehir Osmanlı'nın ilk büyük başkenti oldu." },
      { year: "1353", digits: "1353", name: "Rumeli'ye Geçiş",
        note: "Orhan Bey'in oğlu Süleyman Paşa Gelibolu'daki Çimpe Kalesi'ne yerleşti; Osmanlı Rumeli'ye ayak bastı." },
      { year: "1361", digits: "1361", name: "Edirne'nin Fethi",
        note: "Edirne alındı; kısa süre sonra başkent olan şehir Balkanlar'daki ilerleyişin merkezi oldu." },
      { year: "1364", digits: "1364", name: "Sırpsındığı Savaşı",
        note: "Edirne'yi geri almak isteyen Haçlı ordusu Meriç kıyısında bozguna uğratıldı; Osmanlı'nın Haçlılara karşı ilk büyük savaşı." },
      { year: "1389", digits: "1389", name: "I. Kosova Savaşı",
        note: "I. Murad Balkan ittifakını yendi; savaş alanında şehit düşen tek Osmanlı padişahı oldu." },
      { year: "1396", digits: "1396", name: "Niğbolu Savaşı",
        note: "Yıldırım Bayezid büyük bir Haçlı ordusunu Niğbolu'da bozguna uğrattı." },
      { year: "1402", digits: "1402", name: "Ankara Savaşı",
        note: "Timur Yıldırım Bayezid'i yendi; Osmanlı'da on bir yıl sürecek Fetret Devri başladı." },
      { year: "1444", digits: "1444", name: "Varna Savaşı",
        note: "II. Murad Haçlı ordusunu yendi; Macar kralı savaşta hayatını kaybetti." },
      { year: "1448", digits: "1448", name: "II. Kosova Savaşı",
        note: "II. Murad Hunyadi Yanoş'un ordusunu yendi; Balkanlar'da Osmanlı hâkimiyeti pekişti." },
      { year: "1453", digits: "1453", name: "İstanbul'un Fethi",
        note: "Fatih Sultan Mehmed İstanbul'u fethetti; Bizans İmparatorluğu sona erdi." },
      { year: "1461", digits: "1461", name: "Trabzon'un Fethi",
        note: "Fatih, Trabzon Rum İmparatorluğu'na son verdi; Karadeniz kıyıları Osmanlı'ya geçti." },
      { year: "1473", digits: "1473", name: "Otlukbeli Savaşı",
        note: "Fatih, Akkoyunlu hükümdarı Uzun Hasan'ı yendi; Anadolu'da Türk birliği güçlendi." },
      { year: "1475", digits: "1475", name: "Kırım'ın Fethi",
        note: "Gedik Ahmed Paşa'nın seferiyle Kırım Hanlığı Osmanlı'ya bağlandı; Karadeniz'de Osmanlı hâkimiyeti kuruldu." },
    ],
  },
  {
    title: "Osmanlı: Zirve ve Değişim",
    rowColors: ["#dfe3e8", "#c3c9d1", "#a5adb8", "#868f9c", "#666f7d", "#4a505d", "#333740"],
    levels: [
      { year: "1514", digits: "1514", name: "Çaldıran Savaşı",
        note: "Yavuz Sultan Selim Safevi hükümdarı Şah İsmail'i yendi; Doğu Anadolu güvence altına alındı." },
      { year: "1516", digits: "1516", name: "Mercidabık Savaşı",
        note: "Yavuz Memlükleri yendi; Suriye Osmanlı topraklarına katıldı." },
      { year: "1517", digits: "1517", name: "Ridaniye Savaşı",
        note: "Yavuz Sultan Selim Memlükleri Ridaniye'de yendi; Mısır alındı ve halifelik Osmanlı'ya geçti." },
      { year: "1521", digits: "1521", name: "Belgrad'ın Fethi",
        note: "Kanuni'nin ilk seferinde Belgrad fethedildi; Orta Avrupa'nın kapısı açıldı." },
      { year: "1522", digits: "1522", name: "Rodos'un Fethi",
        note: "Kanuni Rodos'u fethetti; Doğu Akdeniz'deki deniz yolu güvence altına alındı." },
      { year: "1526", digits: "1526", name: "Mohaç Meydan Muharebesi",
        note: "Kanuni Sultan Süleyman Macar ordusunu iki saati bulmayan bir savaşta yendi." },
      { year: "1529", digits: "1529", name: "I. Viyana Kuşatması",
        note: "Kanuni Viyana'yı kuşattı; kışın yaklaşmasıyla ordu kuşatmayı kaldırıp geri döndü." },
      { year: "1538", digits: "1538", name: "Preveze Deniz Savaşı",
        note: "Barbaros Hayreddin Paşa Haçlı donanmasını yendi; Akdeniz'de Osmanlı üstünlüğü kuruldu." },
      { year: "1555", digits: "1555", name: "Amasya Antlaşması",
        note: "Safevilerle imzalanan ilk resmî antlaşmayla iki devlet arasındaki sınır belirlendi." },
      { year: "1571", digits: "1571", name: "Kıbrıs'ın Fethi",
        note: "Lala Mustafa Paşa komutasındaki ordu Kıbrıs'ı fethetti." },
      { year: "1606", digits: "1606", name: "Zitvatorok Antlaşması",
        note: "Avusturya ile imzalanan antlaşmayla Avusturya arşidükü Osmanlı padişahına denk sayıldı; Osmanlı'nın Batı karşısındaki üstünlüğü sarsıldı." },
      { year: "1639", digits: "1639", name: "Kasr-ı Şirin Antlaşması",
        note: "IV. Murad'ın Bağdat'ı geri almasının ardından İran ile imzalandı; bugünkü Türkiye–İran sınırının temeli atıldı." },
      { year: "1683", digits: "1683", name: "II. Viyana Kuşatması",
        note: "Merzifonlu Kara Mustafa Paşa'nın kuşatması başarısız oldu; Osmanlı'nın Avrupa'da geri çekilişi başladı." },
      { year: "1774", digits: "1774", name: "Küçük Kaynarca Antlaşması",
        note: "Rusya ile imzalanan antlaşmayla Kırım bağımsız oldu; Osmanlı ilk kez Müslüman nüfuslu bir toprağını kaybetti." },
      { year: "1839", digits: "1839", name: "Tanzimat Fermanı",
        note: "Can, mal ve namus güvencesi ile kanun önünde eşitlik ilkesi ilan edildi." },
      { year: "1876", digits: "1876", name: "I. Meşrutiyet",
        note: "Kanun-ı Esasi ilan edildi: Türk tarihinin ilk anayasası ve ilk meclisi." },
      { year: "1877", digits: "1877", name: "93 Harbi",
        note: "Rumi 1293 yılına denk geldiği için '93 Harbi' denen Osmanlı–Rus Savaşı; Plevne savunması destanlaştı." },
    ],
  },
  {
    title: "Meşrutiyet'ten Cumhuriyet'e",
    rowColors: ["#f3d6d6", "#e9a9a9", "#dc7676", "#c94b4b", "#a93636", "#822828", "#5c1c1c"],
    levels: [
      { year: "1908", digits: "1908", name: "II. Meşrutiyet",
        note: "Kanun-ı Esasi yeniden yürürlüğe girdi ve meclis yeniden açıldı." },
      { year: "1911", digits: "1911", name: "Trablusgarp Savaşı",
        note: "İtalya'nın Trablusgarp'a saldırısına karşı Mustafa Kemal'in de aralarında olduğu gönüllü subaylar direniş örgütledi." },
      { year: "1912", digits: "1912", name: "Balkan Savaşları",
        note: "Balkan devletlerinin saldırısıyla Osmanlı Rumeli'deki topraklarının büyük kısmını kaybetti." },
      { year: "1914", digits: "1914", name: "I. Dünya Savaşı",
        note: "Osmanlı Devleti İttifak Devletleri'nin yanında I. Dünya Savaşı'na girdi." },
      { year: "1915", digits: "1915", name: "Çanakkale Savaşları",
        note: "18 Mart'ta İtilaf donanması Boğaz'ı geçemedi; kara savaşlarıyla birlikte 'Çanakkale geçilmez' destanı yazıldı." },
      { year: "1916", digits: "1916", name: "Kut'ül-Amare Zaferi",
        note: "Irak cephesinde kuşatılan İngiliz ordusu teslim oldu; savaşın en önemli Osmanlı zaferlerinden biri." },
      { year: "1919", digits: "1919", name: "Samsun'a Çıkış",
        note: "19 Mayıs'ta Mustafa Kemal Samsun'a çıktı; Millî Mücadele başladı." },
      { year: "1920", digits: "1920", name: "TBMM'nin Açılışı",
        note: "23 Nisan'da Türkiye Büyük Millet Meclisi Ankara'da açıldı." },
      { year: "1921", digits: "1921", name: "Sakarya Meydan Muharebesi",
        note: "22 gün 22 gece süren muharebenin sonunda Yunan ordusu geri çekildi; Mustafa Kemal'e Mareşal rütbesi ve Gazi unvanı verildi." },
      { year: "1922", digits: "1922", name: "Büyük Taarruz",
        note: "26 Ağustos'ta başlayan taarruz, 30 Ağustos Başkomutanlık Meydan Muharebesi ile zaferle sonuçlandı." },
      { year: "1923", digits: "1923", name: "Cumhuriyetin İlanı",
        note: "29 Ekim'de Cumhuriyet ilan edildi; Mustafa Kemal Atatürk ilk Cumhurbaşkanı seçildi." },
      { year: "1939", digits: "1939", name: "Hatay'ın Katılımı",
        note: "Hatay Devlet Meclisi'nin kararıyla Hatay Türkiye'ye katıldı." },
    ],
  },
];
