// History mode: a chronological campaign from the Asian Huns to the Republic.
// Each level's bricks spell out the event's year; the note is shown on a text
// card before the level starts. Each era has its own brick palette (top → bottom
// row) so the campaign visibly moves through time without background images.
const HISTORY_CHAPTERS = [
  {
    title: "İlk Türk Devletleri",
    rowColors: ["#f5ddb0", "#e8c288", "#d1a165", "#b17f48", "#8c6238", "#664829", "#40301c"],
    levels: [
      { year: "MÖ 220", digits: "220", name: "Büyük Hun Devleti",
        note: "Bilinen ilk Türk devleti Teoman Yabgu döneminde tarih sahnesine çıktı." },
      { year: "MÖ 209", digits: "209", name: "Mete Han",
        note: "Mete Han tahta geçti; orduyu onlu sisteme göre düzenleyerek Hunları bozkırın en güçlü devleti yaptı." },
      { year: "375", digits: "375", name: "Kavimler Göçü",
        note: "Balamir önderliğindeki Hunlar Karadeniz'in kuzeyine ilerledi; başlayan göç dalgası Avrupa'nın haritasını değiştirdi." },
      { year: "552", digits: "552", name: "Göktürk Devleti",
        note: "Bumin Kağan Avarları yenerek Göktürk Devleti'ni kurdu. 'Türk' adını resmî devlet adı olarak kullanan ilk devlet." },
      { year: "630", digits: "630", name: "Fetret Yılları",
        note: "Doğu Göktürkleri Çin hâkimiyetine girdi; bağımsızlık mücadelesi yaklaşık yarım yüzyıl sürdü." },
      { year: "682", digits: "682", name: "II. Göktürk Devleti",
        note: "Kutluk (İlteriş) Kağan Çin egemenliğine son verip II. Göktürk Devleti'ni kurdu." },
      { year: "744", digits: "744", name: "Uygur Devleti",
        note: "Uygurlar Göktürk Devleti'nin yerine kendi devletlerini kurdu; şehirler kuran, yerleşik hayata geçen bir Türk devleti oldular." },
      { year: "751", digits: "751", name: "Talas Savaşı",
        note: "Karlukların desteklediği Abbasi ordusu Çin'i yendi; Orta Asya'da Türk–İslam yakınlaşması hızlandı." },
    ],
  },
  {
    title: "Selçuklular",
    rowColors: ["#e8e2d0", "#cfc4a8", "#b8a06c", "#9c8354", "#7c6a42", "#5a4a30", "#3a3020"],
    levels: [
      { year: "1040", digits: "1040", name: "Dandanakan Savaşı",
        note: "Tuğrul ve Çağrı Beyler Gaznelileri yendi; Büyük Selçuklu Devleti resmen kuruldu." },
      { year: "1071", digits: "1071", name: "Malazgirt Meydan Muharebesi",
        note: "Sultan Alparslan Bizans İmparatoru Romen Diyojen'i yendi; Anadolu'nun kapıları Türklere açıldı." },
      { year: "1176", digits: "1176", name: "Miryokefalon Savaşı",
        note: "II. Kılıç Arslan Bizans'ı yendi; Bizans Anadolu'yu geri alma umudunu yitirdi." },
      { year: "1243", digits: "1243", name: "Kösedağ Savaşı",
        note: "Anadolu Selçukluları Moğollara yenildi; Anadolu'da beylikler dönemine giden yol açıldı." },
    ],
  },
  {
    title: "Osmanlı: Kuruluş ve Yükseliş",
    rowColors: ["#f2d9a0", "#e0b876", "#c99356", "#a8703f", "#7a4f34", "#523829", "#33241c"],
    levels: [
      { year: "1299", digits: "1299", name: "Osmanlı Beyliği",
        note: "Osman Bey önderliğinde Osmanlı Beyliği kuruldu (geleneksel kuruluş tarihi)." },
      { year: "1326", digits: "1326", name: "Bursa'nın Fethi",
        note: "Orhan Bey Bursa'yı aldı; şehir Osmanlı'nın ilk büyük başkenti oldu." },
      { year: "1361", digits: "1361", name: "Edirne'nin Fethi",
        note: "Edirne alındı; kısa süre sonra başkent olan şehir Balkanlar'daki ilerleyişin merkezi oldu." },
      { year: "1389", digits: "1389", name: "I. Kosova Savaşı",
        note: "I. Murad Balkan ittifakını yendi; savaş alanında şehit düşen tek Osmanlı padişahı oldu." },
      { year: "1396", digits: "1396", name: "Niğbolu Savaşı",
        note: "Yıldırım Bayezid büyük bir Haçlı ordusunu Niğbolu'da bozguna uğrattı." },
      { year: "1402", digits: "1402", name: "Ankara Savaşı",
        note: "Timur Yıldırım Bayezid'i yendi; Osmanlı'da on bir yıl sürecek Fetret Devri başladı." },
      { year: "1444", digits: "1444", name: "Varna Savaşı",
        note: "II. Murad Haçlı ordusunu yendi; Macar kralı savaşta hayatını kaybetti." },
      { year: "1448", digits: "1448", name: "II. Kosova Savaşı",
        note: "II. Murad Hunyadi Yanoş'un ordusunu yendi; Balkanlar'da Osmanlı hâkimiyeti pekişti." },
      { year: "1453", digits: "1453", name: "İstanbul'un Fethi",
        note: "Fatih Sultan Mehmed İstanbul'u fethetti; Bizans İmparatorluğu sona erdi." },
      { year: "1461", digits: "1461", name: "Trabzon'un Fethi",
        note: "Fatih, Trabzon Rum İmparatorluğu'na son verdi; Karadeniz kıyıları Osmanlı'ya geçti." },
      { year: "1473", digits: "1473", name: "Otlukbeli Savaşı",
        note: "Fatih, Akkoyunlu hükümdarı Uzun Hasan'ı yendi; Anadolu'da Türk birliği güçlendi." },
    ],
  },
  {
    title: "Osmanlı: Zirve ve Değişim",
    rowColors: ["#dfe3e8", "#c3c9d1", "#a5adb8", "#868f9c", "#666f7d", "#4a505d", "#333740"],
    levels: [
      { year: "1514", digits: "1514", name: "Çaldıran Savaşı",
        note: "Yavuz Sultan Selim Safevi hükümdarı Şah İsmail'i yendi; Doğu Anadolu güvence altına alındı." },
      { year: "1516", digits: "1516", name: "Mercidabık Savaşı",
        note: "Yavuz Memlükleri yendi; Suriye Osmanlı topraklarına katıldı." },
      { year: "1526", digits: "1526", name: "Mohaç Meydan Muharebesi",
        note: "Kanuni Sultan Süleyman Macar ordusunu iki saati bulmayan bir savaşta yendi." },
      { year: "1538", digits: "1538", name: "Preveze Deniz Savaşı",
        note: "Barbaros Hayreddin Paşa Haçlı donanmasını yendi; Akdeniz'de Osmanlı üstünlüğü kuruldu." },
      { year: "1683", digits: "1683", name: "II. Viyana Kuşatması",
        note: "Merzifonlu Kara Mustafa Paşa'nın kuşatması başarısız oldu; Osmanlı'nın Avrupa'da geri çekilişi başladı." },
      { year: "1774", digits: "1774", name: "Küçük Kaynarca Antlaşması",
        note: "Rusya ile imzalanan antlaşmayla Kırım bağımsız oldu; Osmanlı ilk kez Müslüman nüfuslu bir toprağını kaybetti." },
      { year: "1839", digits: "1839", name: "Tanzimat Fermanı",
        note: "Can, mal ve namus güvencesi ile kanun önünde eşitlik ilkesi ilan edildi." },
      { year: "1876", digits: "1876", name: "I. Meşrutiyet",
        note: "Kanun-ı Esasi ilan edildi: Türk tarihinin ilk anayasası ve ilk meclisi." },
    ],
  },
  {
    title: "Millî Mücadele ve Cumhuriyet",
    rowColors: ["#f3d6d6", "#e9a9a9", "#dc7676", "#c94b4b", "#a93636", "#822828", "#5c1c1c"],
    levels: [
      { year: "1915", digits: "1915", name: "Çanakkale Savaşları",
        note: "18 Mart'ta İtilaf donanması Boğaz'ı geçemedi; kara savaşlarıyla birlikte 'Çanakkale geçilmez' destanı yazıldı." },
      { year: "1919", digits: "1919", name: "Samsun'a Çıkış",
        note: "19 Mayıs'ta Mustafa Kemal Samsun'a çıktı; Millî Mücadele başladı." },
      { year: "1920", digits: "1920", name: "TBMM'nin Açılışı",
        note: "23 Nisan'da Türkiye Büyük Millet Meclisi Ankara'da açıldı." },
      { year: "1922", digits: "1922", name: "Büyük Taarruz",
        note: "26 Ağustos'ta başlayan taarruz, 30 Ağustos Başkomutanlık Meydan Muharebesi ile zaferle sonuçlandı." },
      { year: "1923", digits: "1923", name: "Cumhuriyetin İlanı",
        note: "29 Ekim'de Cumhuriyet ilan edildi; Mustafa Kemal Atatürk ilk Cumhurbaşkanı seçildi." },
    ],
  },
];
